package source

import (
	"encoding/xml"
)


// Generated by zek (https://github.com/miku/zek)
type XMLResult struct {
	XMLName            xml.Name `xml:"incident"`
	Filename           string   `xml:"filename,attr"`
	Version            string   `xml:"version,attr"`
	Time               string   `xml:"time,attr"`
	OneminIncidentData struct {
		IncidentData []struct {
			Incident struct {
				IncTypeName   string `xml:"inc_type_name,attr"`
				IncName       string `xml:"inc_name,attr"`
				IncTime       string `xml:"inc_time,attr"`
				IncidentId    string `xml:"incidentId,attr"`
				FreewayId     string `xml:"freewayId,attr"`
				ExpresswayId  string `xml:"expresswayId,attr"`
				DirectionId   string `xml:"directionId,attr"`
				IncLocation   string `xml:"inc_location,attr"`
				FromMilepost  string `xml:"from_milepost,attr"`
				ToMilepost    string `xml:"to_milepost,attr"`
				Interchange   string `xml:"interchange,attr"`
				IncBlockage   string `xml:"inc_blockage,attr"`
				IncSeverity   string `xml:"inc_severity,attr"`
				IncNotifyTime string `xml:"inc_notify_time,attr"`
				IncNotifyMode string `xml:"inc_notify_mode,attr"`
				IncEndTime    string `xml:"inc_end_time,attr"`
				IncStepNo     string `xml:"inc_stepNo,attr"`
				IncStepTime   string `xml:"inc_step_time,attr"`
			} `xml:"incident"`
		} `xml:"incident_data"`
	} `xml:"onemin_incident_data"`
}
